### PR TITLE
chore: converge on go-jose

### PR DESCRIPTION
**Pull request by RTann**
`github.com/dgrijalva/jwt-go` is old and archived in favor of `github.com/golang-jwt/jwt`

`gopkg.in/square/go-jose.v2` is old and archived in favor of `github.com/go-jose/go-jose`

Honestly wasn't sure which one to pick, so I opted for `go-jose` because it seemed like it had the nicer interface. The stackrox/stackrox repo also uses both, but mostly `go-jose` so that helps with this decision, too.

If anyone knows a good way to test this, please let me know

### CODE REVIEW

**Comment by RTann** [comment]
I am testing the dev server, and I found it seems ok until I run `make pull-infractl-from-dev-server`. This command fails every time and, more-or-less, kills the server. It's still up, but it's essentially useless.

```
$ make pull-infractl-from-dev-server
set -o pipefail; \
	curl --retry 3 --insecure --silent --show-error --fail --location https://localhost:8443/v1/cli/darwin/amd64/upgrade \
          | jq -r ".result.fileChunk" \
          | base64 -d \
          > bin/infractl
/usr/bin/base64: I/O error on input
curl: (23) Failure writing output to destination
make: *** [pull-infractl-from-dev-server] Error 141
```

Anyone know why this may be?

Otherwise, I can see my auth token (different from my prod one)

**Comment by tommartensen** [comment]
> 
```
$ make pull-infractl-from-dev-server
set -o pipefail; \
	curl --retry 3 --insecure --silent --show-error --fail --location https://localhost:8443/v1/cli/darwin/amd64/upgrade \
          | jq -r ".result.fileChunk" \
          | base64 -d \
          > bin/infractl
/usr/bin/base64: I/O error on input
curl: (23) Failure writing output to destination
make: *** [pull-infractl-from-dev-server] Error 141
```

> Anyone know why this may be?

No, but it works for me™. i/o error could be because the curl or jq are failing. If you want to debug this, check if you can see any error from curl or jq.

**Review by tommartensen — APPROVED** [review]

**Comment by RTann** [comment]
Since I ran into issues locally but Tom didn't, I'd like to get at least one more reviewer to take a look and try testing this, if possible. Thank!

**Comment by RTann** [comment]
Also, when I tested it, I noticed the token differed from my prod token, so I think when/if this is merged, we'll have to inform everyone they may need to update their tokens locally

**Comment by tommartensen** [comment]
> Also, when I tested it, I noticed the token differed from my prod token, so I think when/if this is merged, we'll have to inform everyone they may need to update their tokens locally

The token on the `/downloads` page or `infractl token` is regenerated every time you open the page or run the command. There is no need to update every token or something.

**Comment by gavin-stackrox** [comment]
> ```
> make pull-infractl-from-dev-server
> ```

works for me also.

**Review by gavin-stackrox — APPROVED** [review]

**Pull request merged**
